export const ROLES = {
  STUDENT: 'STUDENT',
  HIRING_MANAGER: 'HIRING_MANAGER',
};

export const JOB_SOURCES = {
  INTERNAL: 'INTERNAL',
  LINKEDIN: 'LINKEDIN',
  NAUKRI: 'NAUKRI',
  INTERNSHALA: 'INTERNSHALA',
  UNSTOP: 'UNSTOP',
};
